version: '3'
services:

  backend:
    container_name: fastapi_d
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:backend --host 0.0.0.0 --port 8000 --reload
    stdin_open: true
    tty: true
    ports:
      - 8080:8000
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/code

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "diary_db"
      POSTGRES_USER: "diary_admin"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - 5000:5432

volumes:
  postgres: