version: '3'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:backend --host 0.0.0.0 --port 8000 --reload
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - .:/code

  mongo:
    image: mongo:latest
    container_name: mongo_fuzzy_db
    env_file:
      - backend/.env
    volumes:
      - mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '6000:27017'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mongo: